CREATE TABLE personas.personas (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    identificacion VARCHAR(255) UNIQUE,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    telefono VARCHAR(255),
    rol VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE
);

CREATE TABLE ubicaciones.departamentos (
    id_departamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_departamento VARCHAR(255) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ubicaciones.ubicaciones (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ubicacion VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    edificio VARCHAR(255),
    piso VARCHAR(255),
    oficina_ambiente VARCHAR(255),
    palabras_clave_ubicacion TEXT,
    ubicacion_manual TEXT,
    id_edificio BIGINT,
    id_piso BIGINT,
    id_ambiente BIGINT,
    id_estacion BIGINT,
    id_usuario_creacion BIGINT,
    id_usuario_ultima_modificacion BIGINT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_ubicacion_componentes UNIQUE (edificio, piso, oficina_ambiente)
);
