-- Parametros del sistema y estado de seeds

CREATE TABLE configuracion.parametros_sistema (
    clave VARCHAR(255) NOT NULL PRIMARY KEY,
    valor VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE configuracion.seed_file_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo VARCHAR(255) NOT NULL UNIQUE,
    ruta_archivo VARCHAR(500) NOT NULL,
    tipo_seed VARCHAR(100) NOT NULL,
    hash_contenido VARCHAR(64) NOT NULL,
    fecha_primera_carga TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_carga TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    cantidad_recargas INTEGER DEFAULT 1,
    activo BOOLEAN DEFAULT TRUE
);
