-- Categorías y Plantillas ML

CREATE TABLE inventario.tipos_atributo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_atributo VARCHAR(255) NOT NULL UNIQUE,
    tipo_dato VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventario.categorias (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(255) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    icono VARCHAR(255),
    color VARCHAR(255),
    estado BOOLEAN DEFAULT TRUE NOT NULL,
    visible BOOLEAN NOT NULL DEFAULT FALSE,
    es_inteligente BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_usuario_creacion BIGINT NOT NULL REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE
);

CREATE TABLE inventario.plantillas_categoria (
    id_plantilla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plantilla_seed VARCHAR(255) UNIQUE,
    nombre_plantilla VARCHAR(255) NOT NULL UNIQUE,
    version VARCHAR(50),
    descripcion TEXT,
    categoria_semantica VARCHAR(150),
    json_scoring JSONB,
    json_reconocimiento JSONB,
    json_patrones JSONB,
    json_inteligencia JSONB,
    json_aprendizaje JSONB,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_usuario_creacion BIGINT NOT NULL REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE
);

CREATE TABLE inventario.categoria_atributos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria BIGINT NOT NULL REFERENCES inventario.categorias(id_categoria) ON DELETE CASCADE,
    id_tipo_atributo BIGINT NOT NULL REFERENCES inventario.tipos_atributo(id) ON DELETE CASCADE,
    etiqueta VARCHAR(255) NOT NULL,
    es_requerido BOOLEAN DEFAULT FALSE NOT NULL,
    valor_defecto VARCHAR(255),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_categoria, id_tipo_atributo)
);

CREATE TABLE inventario.plantilla_atributos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plantilla BIGINT NOT NULL REFERENCES inventario.plantillas_categoria(id_plantilla) ON DELETE CASCADE,
    id_tipo_atributo BIGINT NOT NULL REFERENCES inventario.tipos_atributo(id) ON DELETE CASCADE,
    etiqueta VARCHAR(255) NOT NULL,
    es_requerido BOOLEAN DEFAULT FALSE NOT NULL,
    orden_ui INT,
    placeholder VARCHAR(255),
    json_extraccion JSONB,
    json_validacion JSONB,
    json_opciones JSONB,
    UNIQUE (id_plantilla, id_tipo_atributo)
);
