-- Edificios, Pisos, Ambientes, Estaciones

CREATE TABLE estructuras.tipos_estructura (
    id_tipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nivel_aplicable VARCHAR(20) NOT NULL,
    descripcion TEXT,
    icono VARCHAR(100),
    color VARCHAR(50),
    configuracion_campos JSONB,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estructuras.edificios (
    id_edificio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    id_tipo_estructura BIGINT REFERENCES estructuras.tipos_estructura(id_tipo),
    direccion TEXT,
    numero_pisos INTEGER,
    area_total_m2 DECIMAL(10,2),
    ano_construccion INTEGER,
    observaciones TEXT,
    propiedades_adicionales JSONB,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_responsable_mantenimiento BIGINT NOT NULL REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE
);

CREATE TABLE estructuras.pisos (
    id_piso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    codigo VARCHAR(100) NOT NULL,
    id_tipo_estructura BIGINT REFERENCES estructuras.tipos_estructura(id_tipo),
    id_edificio BIGINT NOT NULL REFERENCES estructuras.edificios(id_edificio) ON DELETE CASCADE,
    numero_piso INTEGER NOT NULL,
    observaciones TEXT,
    propiedades_adicionales JSONB,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_responsable_mantenimiento BIGINT NOT NULL REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_edificio_codigo UNIQUE(id_edificio, codigo),
    CONSTRAINT uk_edificio_numero UNIQUE(id_edificio, numero_piso)
);

CREATE TABLE estructuras.ambientes (
    id_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    codigo VARCHAR(100) NOT NULL,
    id_piso BIGINT NOT NULL REFERENCES estructuras.pisos(id_piso) ON DELETE CASCADE,
    id_tipo_estructura BIGINT REFERENCES estructuras.tipos_estructura(id_tipo),
    palabras_clave_ubicacion TEXT,
    capacidad_personas INTEGER,
    observaciones TEXT,
    propiedades_adicionales JSONB,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_responsable BIGINT NOT NULL REFERENCES seguridad.usuarios(id_usuario),
    id_departamento_responsable BIGINT REFERENCES ubicaciones.departamentos(id_departamento),
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_piso_codigo UNIQUE(id_piso, codigo)
);

CREATE TABLE estructuras.estaciones (
    id_estacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    codigo VARCHAR(100) NOT NULL,
    id_ambiente BIGINT NOT NULL REFERENCES estructuras.ambientes(id_ambiente) ON DELETE CASCADE,
    id_tipo_estructura BIGINT NOT NULL DEFAULT 1 REFERENCES estructuras.tipos_estructura(id_tipo),
    id_responsable BIGINT REFERENCES personas.personas(id_persona),
    capacidad_bienes INTEGER DEFAULT 10,
    observaciones TEXT,
    propiedades_adicionales JSONB,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_ambiente_codigo UNIQUE(id_ambiente, codigo)
);

CREATE TABLE estructuras.componentes_estaciones (
    id_componente BIGSERIAL PRIMARY KEY,
    id_estacion BIGINT NOT NULL REFERENCES estructuras.estaciones(id_estacion) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('EQUIPO_COMPLETO', 'PERIFERICO', 'COMPONENTE_SUELTO')),
    categoria_base VARCHAR(100),
    descripcion TEXT,
    orden INTEGER DEFAULT 1,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_eliminacion TIMESTAMP WITH TIME ZONE
);
