-- Tabla principal de bienes y registros de actividad

CREATE TABLE inventario.bienes (
    id_bien BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_bien VARCHAR(255) NOT NULL,
    caf VARCHAR(255) NOT NULL,
    numero_serie VARCHAR(255),
    observaciones TEXT,
    estado_fisico VARCHAR(100),
    estado_operacional VARCHAR(100),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_categoria BIGINT NOT NULL REFERENCES inventario.categorias(id_categoria),
    id_ubicacion_actual BIGINT NOT NULL REFERENCES ubicaciones.ubicaciones(id_ubicacion),
    id_responsable_actual BIGINT REFERENCES personas.personas(id_persona),
    id_departamento BIGINT NOT NULL REFERENCES ubicaciones.departamentos(id_departamento),
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE
);

CREATE TABLE estructuras.bienes_estaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bien BIGINT NOT NULL REFERENCES inventario.bienes(id_bien) ON DELETE CASCADE,
    id_estacion BIGINT NOT NULL REFERENCES estructuras.estaciones(id_estacion) ON DELETE CASCADE,
    id_componente BIGINT REFERENCES estructuras.componentes_estaciones(id_componente),
    posicion_relativa VARCHAR(100),
    observaciones TEXT,
    id_usuario_asignacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_asignacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_desasignacion TIMESTAMP WITH TIME ZONE
);

CREATE TABLE inventario.bien_atributos_valores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bien BIGINT NOT NULL REFERENCES inventario.bienes(id_bien) ON DELETE CASCADE,
    id_atributo BIGINT NOT NULL REFERENCES inventario.tipos_atributo(id),
    valor TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_bien, id_atributo)
);

-- Historial de ubicaciones (pendiente de implementacion)
CREATE TABLE inventario.historial_ubicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bien BIGINT NOT NULL REFERENCES inventario.bienes(id_bien) ON DELETE CASCADE,
    id_ubicacion BIGINT NOT NULL REFERENCES ubicaciones.ubicaciones(id_ubicacion),
    id_usuario_registro BIGINT NOT NULL REFERENCES seguridad.usuarios(id_usuario),
    fecha_entrada TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_salida TIMESTAMP WITH TIME ZONE,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auditoria.registros_actividad (
    id_registro BIGSERIAL PRIMARY KEY,
    tipo_operacion VARCHAR(50) NOT NULL,
    tipo_endpoint VARCHAR(50) NOT NULL,
    entidad_afectada VARCHAR(100),
    entidad_id BIGINT,
    descripcion TEXT NOT NULL,
    metadatos JSONB,
    ip_address VARCHAR(45),
    user_agent TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_usuario BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_creacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    id_usuario_ultima_modificacion BIGINT REFERENCES seguridad.usuarios(id_usuario),
    fecha_operacion TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_ultima_modificacion TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_eliminacion TIMESTAMP
);

ALTER TABLE ubicaciones.ubicaciones
    ADD CONSTRAINT fk_ubicacion_usuario_creacion FOREIGN KEY (id_usuario_creacion) REFERENCES seguridad.usuarios(id_usuario),
    ADD CONSTRAINT fk_ubicacion_usuario_modificacion FOREIGN KEY (id_usuario_ultima_modificacion) REFERENCES seguridad.usuarios(id_usuario),
    ADD CONSTRAINT fk_ubicacion_edificio FOREIGN KEY (id_edificio) REFERENCES estructuras.edificios(id_edificio),
    ADD CONSTRAINT fk_ubicacion_piso FOREIGN KEY (id_piso) REFERENCES estructuras.pisos(id_piso),
    ADD CONSTRAINT fk_ubicacion_ambiente FOREIGN KEY (id_ambiente) REFERENCES estructuras.ambientes(id_ambiente),
    ADD CONSTRAINT fk_ubicacion_estacion FOREIGN KEY (id_estacion) REFERENCES estructuras.estaciones(id_estacion);
